# hmm realy tasty config for realy tasty classification stuff

#the classifier to use
classifier : |
  ensemble.RandomForestClassifier(
      n_estimators=30,
      max_features='sqrt',
      n_jobs=-1,
      max_depth=15,
      criterion='entropy',
  )


# randomly sample the data if you dont want to use the whole set
n_background: 100000
n_signal: 100000

#query to apply to the data before separation
query : 'Leakage < 0.2'

# define the number of cross validations to perform
n_cross_validations : 5

training_variables:
  - 'Size'
  - 'Length'
  - 'Width'
  - 'numIslands'
  - 'Leakage'
  - 'm3l'
  - 'm3t'
  - 'Disp'
  - 'Timespread'
  - 'arrivalTimeMean'
  - 'ConcCore'
