# hmm realy tasty config for realy tasty classification stuff

#the classifier to use
classifier : |
  ensemble.RandomForestClassifier(
      n_estimators=30,
      max_features='sqrt',
      n_jobs=-1,
      max_depth=15,
      criterion='entropy',
  )


# randomly sample the data if you dont want to use the whole set
n_background: 500
n_signal: 500

# define the number of cross validations to perform
n_cross_validations : 5

true_energy: MCorsikaEvtHeader.fTotalEnergy

training_variables:
  - Size
  - Length
  - Width
  - numIslands
  - Leakage
  - m3l
  - m3t
  - Disp
  - Timespread
  - arrivalTimeMean
  - ConcCore

# Generate some features using pd.DataFrame.eval
# List all keys that have to be read from the input files
# in needed keys. 
# features must be a mapping of feature name -> expression
feature_generation:
  needed_keys:
    - Width
    - Length
    - Theta
  features:
    Area: Width * Length * @pi
    Theta2: Theta**2
   
