# hmm realy tasty config for realy tasty classification stuff
#the classifier to use
classifier : |
  ensemble.RandomForestClassifier(
      n_estimators=30,
      max_features='sqrt',
      n_jobs=-1,
      max_depth=15,
      criterion='entropy',
  )


# randomly sample the data if you dont want to use the whole set
n_background: 500
n_signal: 500

# define the number of cross validations to perform
n_cross_validations : 5

true_energy: corsika_evt_header_total_energy

# Define the name of the category you want to find. The default is 'gamma'.
# It will be written as <class_name>_prediction into the file when applying the model.
class_name: gamma

training_variables:
  - size
  - length
  - width
  - num_islands
  - leakage
  - m3l
  - m3t
  - disp
  - timespread
  - arrival_time_mean
  - conc_core
